# 04 - Model Training

This notebook is part of the Blood Donation Prediction project.

# 7. DATA SPLITTING

In [ ]:
# Splitting the training and testing data
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,random_state=13)

In [ ]:
x_train

,Months since Last Donation,Number of Donations,Total Volume Donated (c.c.),Months since First Donation
163,0.859634,0.666667,0.718290,0.456943
13,0.333333,0.528321,0.593954,0.224201
119,0.488325,0.602452,0.661324,0.641280
237,0.859634,0.440643,0.511515,0.578689
152,0.753953,0.666667,0.718290,0.550194
...,...,...,...,...
230,0.821658,0.666667,0.718290,0.833333
16,0.333333,0.333333,0.405259,0.069036
74,0.333333,0.900147,0.917511,0.900521
176,0.821658,0.333333,0.405259,0.347035
338,0.488325,0.194988,0.255573,0.186887

In [ ]:
y_train

213    0
13     1
157    0
302    0
202    0
      ..
294    0
17     1
91     0
228    1
439    0
Name: Made Donation in March 2007, Length: 338, dtype: int64

In [ ]:
x_test

,Months since Last Donation,Number of Donations,Total Volume Donated (c.c.),Months since First Donation
30,0.333333,0.528321,0.593954,0.304738
199,0.821658,1.000000,1.000000,1.000000
27,0.488325,0.602452,0.661324,0.304738
235,0.488325,0.194988,0.255573,0.738565
351,0.488325,0.194988,0.255573,0.258252
...,...,...,...,...
265,0.753953,0.333333,0.405259,0.860736
114,0.488325,0.528321,0.593954,0.530550
275,0.937863,0.440643,0.511515,0.683170
106,0.488325,0.602452,0.661324,0.587949
400,0.821658,0.333333,0.405259,0.530550

In [ ]:
y_test

34     0
254    0
31     1
300    0
464    0
      ..
340    0
151    1
360    0
143    1
537    0
Name: Made Donation in March 2007, Length: 85, dtype: int64

# 8. MODEL CREATION

## 8.1. LOGISTIC REGRESSION

In [ ]:
# initializing the model
LR=LogisticRegression()

# fitting the training data to the model
LR.fit(x_train,y_train)

# predicting the target for testing data
y_pred_LR=LR.predict(x_test)

In [ ]:
# evaluating the model's performance by accuracy_score
lg_rg_acc=accuracy_score(y_test,y_pred_LR)
print(f'Accuracy_Score: {lg_rg_acc}')

Accuracy_Score: 0.8

## 8.2. DECISION TREE

In [ ]:
#initializing the model
DT=DecisionTreeClassifier()

#fitting the training data to the model
DT.fit(x_train,y_train)

#predicting the target for testing data
y_pred_DT=DT.predict(x_test)

In [ ]:
## Evaluating the DecisionTreeClassifier model's performance by Accuracy_Score
Dt_Accuracy_Score=accuracy_score(y_test,y_pred_DT)
print(f'Accuracy_Score:{Dt_Accuracy_Score}')

Accuracy_Score:0.6470588235294118

## 8.2.1. HYPERPARAMETER TUNING (DECISION TREE)

In [ ]:
#creating a dictionary with best parameters
params_dt={'criterion':['gini','entropy','log_loss'],
           'splitter':['best','random'],
           'max_depth':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
           'min_samples_split':list(range(1,20)),
           'min_samples_leaf':list(range(1,20)),
            'max_features': ['sqrt', 'log2'],
            'max_leaf_nodes': [10, 20, 50, 100]}

In [ ]:
#initializing RandomizedSearchCV
DT_CV=RandomizedSearchCV(estimator=DT,
                   param_distributions=params_dt,
                   scoring='accuracy',
                   n_jobs=-1,
                   verbose=3,
                   cv=5
                  )

#fitting the training data to the RandomizedSearchCV
DT_CV.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy',
                                                      'log_loss'],
                                        'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19, 20],
                                        'max_features': ['sqrt', 'log2'],
                                        'max_leaf_nodes': [10, 20, 50, 100],
                                        'min_samples_leaf': [1, 2, 3, 4, 5, 6,
                                                             7, 8, 9, 10, 11,
                                                             12, 13, 14, 15, 16,
                                                             17, 18, 19],
                                        'min_samples_split': [1, 2, 3, 4, 5, 6,
                                                              7, 8, 9, 10, 11,
                                                              12, 13, 14, 15,
                                                              16, 17, 18, 19],
                                        'splitter': ['best', 'random']},
                   scoring='accuracy', verbose=3)

In [ ]:
#getting best hyperparameters
print(f'Best_Params:{DT_CV.best_params_}')

Best_Params:{'splitter': 'random', 'min_samples_split': 5, 'min_samples_leaf': 15, 'max_leaf_nodes': 10, 'max_features': 'log2', 'max_depth': 7, 'criterion': 'entropy'}

In [ ]:
#initializing DecisionTreeClassifier model
DT_Model=DecisionTreeClassifier(splitter= 'random', min_samples_split=5, min_samples_leaf= 15, max_leaf_nodes= 10,
max_features='log2', max_depth= 7, criterion= 'entropy')
#fitting the training data to the model
DT_Model.fit(x_train,y_train)

#predicting the target for testing data
predd_dt=DT_Model.predict(x_test)

#Evaluating the DecisionTreeClassifier model's performance by Accuracy_Score
dt_acc=accuracy_score(y_test,predd_dt)
print(f'Accuracy_Score: {dt_acc}')

Accuracy_Score: 0.8352941176470589

## 8.3. RANDOM FOREST

In [ ]:
#initializing randomforest model
RF=RandomForestClassifier()

#fitting the training data to the model
RF.fit(x_train,y_train)

#predicting the target for testing data
pred_rf=RF.predict(x_test)

In [ ]:
#evaluating the RandomForestClassifier model's performance by Accuracy_Score
Rf_Accuracy_Score=accuracy_score(y_test,pred_rf)
print(f'Accuracy_Score:{Rf_Accuracy_Score}')

Accuracy_Score:0.7294117647058823

## 8.3.1. HYPERPARAMETER TUNING (RANDOM FOREST)

In [ ]:
#creating a dictionary with best parameters
params_rf={'n_estimators': [50,100,150,200,250,300,350,400,450,500],
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': list(range(1,51)),
    'min_samples_split': list(range(1,30)),
    'min_samples_leaf': list(range(1,30)),
    'max_features': ['sqrt', 'log2', None],
    'bootstrap': [True, False],
    'oob_score': [True, False],
    'class_weight': [None, 'balanced']
       }

In [ ]:
#initializing RandomizedSearchCV
RF_CV=RandomizedSearchCV(estimator=RF,
                   param_distributions=params_rf,
                   scoring='accuracy',
                   cv=5,
                   verbose=3,
                   n_jobs=-1
                  )

#fitting the training data into RandomizedSearchCV
RF_CV.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'class_weight': [None, 'balanced'],
                                        'criterion': ['gini', 'entropy',
                                                      'log_loss'],
                                        'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19, 20, 21,
                                                      22, 23, 24, 25, 26, 27,
                                                      28, 29, 30, ...],
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': [1, 2, 3, 4, 5, 6,
                                                             7, 8, 9, 10, 11,
                                                             12, 13, 14, 15, 16,
                                                             17, 18, 19, 20, 21,
                                                             22, 23, 24, 25, 26,
                                                             27, 28, 29],
                                        'min_samples_split': [1, 2, 3, 4, 5, 6,
                                                              7, 8, 9, 10, 11,
                                                              12, 13, 14, 15,
                                                              16, 17, 18, 19,
                                                              20, 21, 22, 23,
                                                              24, 25, 26, 27,
                                                              28, 29],
                                        'n_estimators': [50, 100, 150, 200, 250,
                                                         300, 350, 400, 450,
                                                         500],
                                        'oob_score': [True, False]},
                   scoring='accuracy', verbose=3)

In [ ]:
#getting a best hyperparameter
print(f'Best_Params:{RF_CV.best_params_}')

Best_Params:{'oob_score': False, 'n_estimators': 50, 'min_samples_split': 23, 'min_samples_leaf': 19, 'max_features': 'log2', 'max_depth': 28, 'criterion': 'gini', 'class_weight': None, 'bootstrap': False}

In [ ]:
#initializing RandomForest model
#max_depth=9, max_features='sqrt', min_samples_leaf=5, min_samples_split=4, n_estimators=300
RF_Model=RandomForestClassifier(oob_score= False, n_estimators= 50, min_samples_split= 23, min_samples_leaf= 19, max_features= "log2", max_depth= 28,
criterion='gini', class_weight= None, bootstrap= False)

#fitting the training data to the model
RF_Model.fit(x_train,y_train)

#predicting the target for testing data
pred_rf1=RF_Model.predict(x_test)

#evaluating RandomForestClassifier model's performance by Accuracy_Score
rf_acc=accuracy_score(y_test,pred_rf1)
print(f'Accuracy_Score:{rf_acc}')

Accuracy_Score:0.8117647058823529

In [ ]:
#oob_score= False, n_estimators= 350, min_samples_split= 17, min_samples_leaf= 15, max_features= None, max_depth= 15,
#criterion='entropy', class_weight= None, bootstrap= True - 0.8117647058823529

## 8.4. GRADIENT BOOSTING CLASSIFIER

In [ ]:
gbmodel=GradientBoostingClassifier()
gbmodel.fit(x_train,y_train)
y_pred_gb=gbmodel.predict(x_test)

In [ ]:
#evaluating the XGboostClassifier model's performance by Accuracy_Score
GB_accuracy=accuracy_score(y_test,y_pred_gb)
print(f'Accuracy_Score: {GB_accuracy}')

Accuracy_Score: 0.7294117647058823

## 8.4.1. HYPERPARAMETER TUNING (GRADIENT BOOSTING)

In [ ]:
gb1grid = {
     'n_estimators': [50,100,150,200,250,300,350,400,450,500],
    'learning_rate': [0.0001,0.01,0.02,0.03,0.1,0.2],
    'max_depth': list(range(1,20)),
    'min_samples_split': list(range(1,20)),
    'min_samples_leaf': list(range(1,20)),
    'max_features': ['sqrt', 'log2']
}

gbc=GradientBoostingClassifier()
gb1_cv=RandomizedSearchCV(estimator=gbc,scoring='accuracy',param_distributions=gb1grid,cv=5,verbose=2,n_jobs=-1)
gb1_cv.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=GradientBoostingClassifier(), n_jobs=-1,
                   param_distributions={'learning_rate': [0.0001, 0.01, 0.02,
                                                          0.03, 0.1, 0.2],
                                        'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 3, 4, 5, 6,
                                                             7, 8, 9, 10, 11,
                                                             12, 13, 14, 15, 16,
                                                             17, 18, 19],
                                        'min_samples_split': [1, 2, 3, 4, 5, 6,
                                                              7, 8, 9, 10, 11,
                                                              12, 13, 14, 15,
                                                              16, 17, 18, 19],
                                        'n_estimators': [50, 100, 150, 200, 250,
                                                         300, 350, 400, 450,
                                                         500]},
                   scoring='accuracy', verbose=2)

In [ ]:
bestparamssgb=gb1_cv.best_params_
print(f'best_params:{bestparamssgb}')

best_params:{'n_estimators': 450, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'max_depth': 2, 'learning_rate': 0.02}

In [ ]:
gbk=GradientBoostingClassifier(n_estimators=450, min_samples_split=10, min_samples_leaf=7, max_features='sqrt', max_depth=2, learning_rate=0.02)
gbk.fit(x_train,y_train)
ypred_gbk=gbk.predict(x_test)
gb_acc=accuracy_score(y_test,ypred_gbk)
print(f'Accuracy_Score:{gb_acc}')

Accuracy_Score:0.8235294117647058

# 8.5. XGBOOSTING CLASSIFIER

In [ ]:
#initializing XGBClassifier
XGB=XGBClassifier()

#fitting the training data to the model
XGB.fit(x_train,y_train)

#predicting the target for testing data
pred_XGB=XGB.predict(x_test)

In [ ]:
#evaluating the XGboostClassifier model's performance by Accuracy_Score
XGB_accuracy=accuracy_score(y_test,pred_XGB)
print(f'Accuracy_Score:{XGB_accuracy}')

Accuracy_Score:0.6823529411764706

## 8.5.1. HYPERPARAMETER TUNING (XGBOOSTING)

In [ ]:
#creating a dictionary with hyperparameter
params={'learning_rate': [0.01, 0.05, 0.1],
        'n_estimators': [100, 200, 300],
        'max_depth': list(range(1,50)),
        'gamma': [0, 0.1, 0.2],
        'reg_alpha':[0.0,0.1,0.5,1.0]
       }

In [ ]:
#initializing RandomizedSearchCV
XGB_CV=RandomizedSearchCV(estimator=XGB,
                   param_distributions=params,
                   scoring='accuracy',
                   cv=3,
                   n_jobs=-1,
                   verbose=1)

#fitting the training data into RandomizedSearchCV
XGB_CV.fit(x_train,y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           gamma=None, grow_policy=None,
                                           importance_type=None,
                                           interaction_constraints=None,
                                           learning_rate...
                                           multi_strategy=None,
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None,
                                           random_state=None, ...),
                   n_jobs=-1,
                   param_distributions={'gamma': [0, 0.1, 0.2],
                                        'learning_rate': [0.01, 0.05, 0.1],
                                        'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19, 20, 21,
                                                      22, 23, 24, 25, 26, 27,
                                                      28, 29, 30, ...],
                                        'n_estimators': [100, 200, 300],
                                        'reg_alpha': [0.0, 0.1, 0.5, 1.0]},
                   scoring='accuracy', verbose=1)

In [ ]:
#getting a best hyperparameter
print(f'Best_Params:{XGB_CV.best_params_}')

Best_Params:{'reg_alpha': 1.0, 'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.1, 'gamma': 0.2}

In [ ]:
#initializing RandomForest model
XGB_Model=XGBClassifier(reg_alpha=1.0, gamma=0.2, learning_rate=0.1, max_depth=4, n_estimators=200)

#fitting the training data to the model
XGB_Model.fit(x_train,y_train)

#predicting the target for testing data
pred_XGB_best=XGB_Model.predict(x_test)

In [ ]:
#evaluating the XGboostClassifier model's performance by Accuracy_Score
xg_acc=accuracy_score(y_test,pred_XGB_best)
print(f'Accuracy_Score:{xg_acc}')

Accuracy_Score:0.8

## 8.6. SVC [SUPPORT VECTOR CLASSIFIER]

In [ ]:
#initialiazing SVC model
svc_=SVC()

#fitting the training data to the model
svc_.fit(x_train,y_train)

#predicting the target for the training data
pred_svc=svc_.predict(x_test)

In [ ]:
#evaluating the SVC model's performance by Accuracy_Score
SVC_accuracy=accuracy_score(y_test,pred_svc)
print(f'Accuracy_Score: {SVC_accuracy}')

Accuracy_Score: 0.8470588235294118

## 8.6.1.  HYPERPARAMETER TUNING (SVC)

In [ ]:
# Creating a dictionary with possible Hyperparameters
params={'kernel':['linear','rbf'],
        'degree':[1,2,3,4,5],
        'gamma':['scale', 'auto'],
        'C':[0.1, 1, 10, 100]
        }

In [ ]:
#initializing RandomizedSearchCV
SVC_CV=RandomizedSearchCV(estimator=svc_,
                    param_distributions=params,
                    scoring='accuracy',
                    cv=5,verbose=3,
                    n_jobs=-1)

#fitting a training data into RandomizeddSearchCV
SVC_CV.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
                   param_distributions={'C': [0.1, 1, 10, 100],
                                        'degree': [1, 2, 3, 4, 5],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['linear', 'rbf']},
                   scoring='accuracy', verbose=3)

In [ ]:
#getting a best parameter
print(f'Best Parameters:{SVC_CV.best_params_}')

Best Parameters:{'kernel': 'rbf', 'gamma': 'scale', 'degree': 2, 'C': 1}

In [ ]:
#intializing the model
SVC_Model=SVC(C=1, degree=2, gamma='scale', kernel='rbf')

#fitting the training data to the model
SVC_Model.fit(x_train,y_train)

#predicting the target for the testing data
pred_svc_best=SVC_Model.predict(x_test)

#evaluating the SVC model's performance by Accuracy_Score
svc_acc=accuracy_score(y_test,pred_svc_best)
print(f'Accuracy_Score:{svc_acc}')

Accuracy_Score:0.8470588235294118

## 8.7. KNN [K-NEAREST NEIGHBORS]

In [ ]:
#initialiazing knn model
knn_=KNeighborsClassifier()

#fitting the training data to the model
knn_.fit(x_train,y_train)

#predicting the target for the training data
y_pred_knn=knn_.predict(x_test)

In [ ]:
#evaluating the SVC model's performance by Accuracy_Score
KNN_accuracy=accuracy_score(y_test,y_pred_knn)
print(f'Accuracy_Score: {KNN_accuracy}')

Accuracy_Score: 0.7647058823529411

## 8.7.1. HYPERPARAMETER TUNING (KNN)

In [ ]:
# Creating a dictionary with possible Hyperparameters
knnn_paramss={
    'n_neighbors': [1,2,3,4,5,6, 7,8, 9,10, 11,12,13,14, 15],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski'],
    'p': [1, 2],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': list(range(1,51))
}

k=KNeighborsClassifier()
knn1=RandomizedSearchCV(estimator=k,param_distributions=knnn_paramss,scoring='accuracy',n_jobs=-1,verbose=2,cv=5)
knn1.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'leaf_size': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19, 20, 21,
                                                      22, 23, 24, 25, 26, 27,
                                                      28, 29, 30, ...],
                                        'metric': ['euclidean', 'manhattan',
                                                   'minkowski'],
                                        'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8,
                                                        9, 10, 11, 12, 13, 14,
                                                        15],
                                        'p': [1, 2],
                                        'weights': ['uniform', 'distance']},
                   scoring='accuracy', verbose=2)

In [ ]:
#getting a best parameter
bestparams_knn=knn1.best_params_
print(f'best_parameters:{bestparams_knn}')

best_parameters:{'weights': 'uniform', 'p': 1, 'n_neighbors': 14, 'metric': 'euclidean', 'leaf_size': 47, 'algorithm': 'ball_tree'}

In [ ]:
#intializing the model
knn_model1=KNeighborsClassifier(weights= 'uniform', p= 1, n_neighbors= 14, metric='euclidean', leaf_size= 47, algorithm= 'ball_tree')

#fitting the training data to the model
knn_model1.fit(x_train,y_train)
y_pred_knn1=knn_model1.predict(x_test)
knn_acc=accuracy_score(y_test,y_pred_knn1)
print(f'Accuracy_Score:{knn_acc}')

Accuracy_Score:0.8117647058823529

## 8.8. ANN [ARTIFICIAL NEURAL NETWORK]

In [ ]:
ann_=MLPClassifier()
ann_.fit(x_train,y_train)
ypred_ann=ann_.predict(x_test)

In [ ]:
#evaluating the SVC model's performance by Accuracy_Score
ANN_accuracy=accuracy_score(y_test,ypred_ann)
print(f'Accuracy_Score: {ANN_accuracy}')

Accuracy_Score: 0.8

## 8.8.1. HYPERPARAMETER TUNING (ANN)

In [ ]:
ann_param_grid = {'hidden_layer_sizes': [(100,),(200,),(300,),(400,),(500,),(1000,) ],
              'activation': ['relu', 'tanh', 'logistic'],
              'solver': ['adam', 'lbfgs'],
              'alpha': [0.0001, 0.001, 0.01],
              'learning_rate_init': [0.001, 0.01, 0.1]}

mlp=MLPClassifier()
ann1=RandomizedSearchCV(estimator=mlp,param_distributions=ann_param_grid,scoring='f1',n_jobs=-1,verbose=2,cv=5)
ann1.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=MLPClassifier(), n_jobs=-1,
                   param_distributions={'activation': ['relu', 'tanh',
                                                       'logistic'],
                                        'alpha': [0.0001, 0.001, 0.01],
                                        'hidden_layer_sizes': [(100,), (200,),
                                                               (300,), (400,),
                                                               (500,),
                                                               (1000,)],
                                        'learning_rate_init': [0.001, 0.01,
                                                               0.1],
                                        'solver': ['adam', 'lbfgs']},
                   scoring='f1', verbose=2)

In [ ]:
bestparams_ann=ann1.best_params_
print(f'best_parameters:{bestparams_ann}')

best_parameters:{'solver': 'lbfgs', 'learning_rate_init': 0.001, 'hidden_layer_sizes': (300,), 'alpha': 0.001, 'activation': 'tanh'}

In [ ]:
ann_model2=MLPClassifier(solver= 'lbfgs',learning_rate_init= 0.001, hidden_layer_sizes= (300,), alpha= 0.001, activation= 'tanh')
ann_model2.fit(x_train,y_train)
ypred_ann2=ann_model2.predict(x_test)
ann_acc=accuracy_score(y_test,ypred_ann2)
print(f'Accuracy_Score:{ann_acc}')

Accuracy_Score:0.8